### PR TITLE
Extract translations to add authorsearch_placeholder

### PR DESCRIPTION
**Pull request by cillianderoiste**
Translations for English and French are still required

Refs #SCR-1050

### CODE REVIEW

**Comment by cillianderoiste** [comment]
Note: we're missing French and English translations for:
Rezensionen durchsuchen
Erweiterte Suche verfeinern
Suchresultate – [Anzahl] Rezensionen gefunden
Portalübergreifender Autorenindex
Autorenindex durchsuchen

**Review by reinhardt — CHANGES_REQUESTED** [review]
This PR seems to remove some strings that are still in use, e.g. "Ausstellende Organisation", which is in recensio.contenttypes:/content/schemata.py. Are your checkouts all up-to-date?

**Comment by reinhardt** [comment]
Please also consider rebasing on master; I just merged Hannes' PR.

**Comment by cillianderoiste** [comment]
Oh! I tried updating all the checkouts and to extract and merge the translations again, but I still see some odd things via podiff. I wonder if it's better to close this PR let you handle it. Let me know what you think. Here are the interesting changes:

 msgid "batch_x_items_matching_your_criteria"
-msgstr "${number} Artikel gefunden."
+msgstr "${number} Rezensionen gefunden."

 msgid "title_search_title"
-msgstr "Website durchsuchen"
+msgstr "Rezensionen durchsuchen"

 msgid "edit_your_search_options"
-msgstr "Suchoptionen bearbeiten"
+msgstr "Suchoptionen verfeinern"

+msgid "authorsearch_placeholder"
+msgstr "Autorenindex durchsuchen"

-msgid "Plattform&uuml;bergreifender Autorenindex:"
-msgstr ""

+msgid "Portal&uuml;bergreifender Autorenindex:"
+msgstr ""

**Comment by reinhardt** [comment]
Yes, I'll update the translations now, and next time we have recensio tickets in the sprint we can take a look at your setup together if you want.

**Comment by reinhardt** [comment]
Done in 0e2b4310f57f3b56db7099fee8fe821794f200ca and 128137aa063113597282cd414b61a0810f596db1.

**Pull request closed without merging**
